#!/usr/bin/env node
/*
colour-tokens -- one palette, roles per owner, and the gate that holds them. H15.23 (B255); the palette design ruled
2026-10-01.

TWO LEVELS. The palette (kernel/palette.mjs) holds every colour value, owned by the core, named by Google Material where a
colour is one. Roles say which palette colour each thing uses, declared by its owner: the product's in kernel/theme.mjs
(`CANVAS_ROLES`, `CHROME_ROLES`), the network plugin's in kernel/network-appearance.mjs (`NETWORK_COLOURS`).

ONE VIEW PER OWNER (mission-kit P3): `--write` generates app/tokens.css from the product's roles (`--tok-<role>`) and
network/tokens.css from the network's (`--tok-network-<role>`). A page loads the token files of the owners it composes:
the product page its own, the lab both.

`--check`, in the gate, fails on:
  - a generated file differing from what the roles produce;
  - a role naming no palette colour (resolving it throws);
  - a colour value -- `#hex`, `rgb()`, `rgba()` -- anywhere outside kernel/palette.mjs, in the stylesheets, the client,
    the lab, the kernel or the network plugin (comments are read past, so a comment may name a colour);
  - a stylesheet reading a token its owner may not: app/style.css the product's only, network/network.css the network's
    or the product's.

Usage: node tools/colour-tokens.mjs --check | --write
*/
import fs from 'node:fs';
import path from 'node:path';
import { resolveRole } from '../kernel/palette.mjs';
import { CANVAS_ROLES, CHROME_ROLES } from '../kernel/theme.mjs';
import { NETWORK_COLOURS } from '../kernel/network-appearance.mjs';

const root = path.resolve(import.meta.dirname, '..');
const COLOUR = /#[0-9a-fA-F]{3,8}\b|rgba?\([^)]*\)/g;
const kebab = (k) => k.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

// each owner: its roles, the token prefix it writes under, and the file it writes
const OWNERS = {
	product: { roles: { ...CANVAS_ROLES, ...CHROME_ROLES }, prefix: '--tok-', file: 'app/tokens.css' },
	network: { roles: NETWORK_COLOURS, prefix: '--tok-network-', file: 'network/tokens.css' },
};
// which owners' tokens each stylesheet may read
const SHEETS = { 'app/style.css': ['product'], 'lab/lab.css': ['product', 'network'], 'network/network.css': ['network', 'product'] };

const tokensOf = (owner) => Object.entries(OWNERS[owner].roles).map(([k, role]) => [`${OWNERS[owner].prefix}${kebab(k)}`, resolveRole(role), role]);
function render(owner) {
	const lines = tokensOf(owner).map(([name, value, role]) => `\t${name}: ${value};   /* ${typeof role === 'string' ? role : `${role.colour} at ${role.alpha}`} */`);
	return `/* GENERATED by tools/colour-tokens.mjs from the ${owner}'s colour roles over kernel/palette.mjs -- edit the roles, then run --write. */\n:root {\n${lines.join('\n')}\n}\n`;
}

const SCANNED = [['app/style.css'], ['lab/lab.css'], ['network/network.css'], ...['app/src', 'lab/src', 'kernel', 'network'].map((d) => [d, /\.(m?js)$/])];
const strip = (text, css) => (css ? text.replace(/\/\*[\s\S]*?\*\//g, '') : text.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:'"`])\/\/[^\n]*/g, '$1'));
function scan() {
	const found = [];
	for (const [where, ext] of SCANNED) {
		const files = ext ? fs.readdirSync(path.join(root, where)).filter((f) => ext.test(f)).map((f) => path.join(where, f)) : [where];
		for (const rel of files) {
			if (rel === 'kernel/palette.mjs') continue;
			const css = rel.endsWith('.css');
			const code = strip(fs.readFileSync(path.join(root, rel), 'utf8'), css);
			for (const m of code.matchAll(COLOUR)) found.push(`${rel}: colour value ${m[0]} -- add it to kernel/palette.mjs if it is new, and name it from a role`);
			if (!css) continue;
			const allowed = new Set((SHEETS[rel] ?? []).flatMap((o) => tokensOf(o).map(([name]) => name)));
			for (const m of code.matchAll(/var\((--tok-[\w-]+)\)/g)) if (!allowed.has(m[1])) found.push(`${rel}: ${m[1]} is not a token this sheet's owners declare (${(SHEETS[rel] ?? []).join(', ') || 'none'})`);
		}
	}
	return found;
}

const mode = process.argv[2];
if (process.argv[1] && new URL(import.meta.url).pathname === process.argv[1]) {
	if (mode !== '--check' && mode !== '--write') { console.error('usage: node tools/colour-tokens.mjs --check | --write'); process.exit(2); }
	if (mode === '--write') {
		for (const owner of Object.keys(OWNERS)) fs.writeFileSync(path.join(root, OWNERS[owner].file), render(owner));
		console.log(`colour-tokens: wrote ${Object.values(OWNERS).map((o) => o.file).join(', ')}`);
	} else {
		const problems = [];
		for (const [owner, o] of Object.entries(OWNERS)) {
			const file = path.join(root, o.file);
			if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== render(owner)) problems.push(`${o.file} differs from what the ${owner}'s roles produce; run node tools/colour-tokens.mjs --write`);
		}
		problems.push(...scan());
		if (problems.length) { for (const p of problems) console.error(`  ${p}`); console.error(`colour-tokens: FAIL -- ${problems.length} finding(s)`); process.exit(1); }
		const n = Object.values(OWNERS).reduce((a, o) => a + Object.keys(o.roles).length, 0);
		console.log(`colour-tokens: PASS -- ${n} roles across ${Object.keys(OWNERS).length} owners over one palette; no colour value outside it`);
	}
}
